import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navs/Navbar";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import ImageProvider from "./_providers/ImageProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AIPG Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ImageProvider>
            <Navbar />
            {children}
          </ImageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
